using Lexer.LexemeDefinitions;
using SyntaxAnalyzer;
using SyntaxAnalyzer.Rules;
using System.Collections.Immutable;
using System.Text.RegularExpressions;

namespace MathFlow;
public static class Constants
{
    public static ImmutableList<ILexemeDefinition> LexemeDefinitions => new List<ILexemeDefinition>()
    {
        new RegexLexemeDefinition(new Regex(@"""(?:\\\\|\\""|\\n|\\r|[^""\\])*"""), "String"),
        new RegexLexemeDefinition(new Regex(GetKeywordPattern(_keywords)), "Keyword"),
        new RegexLexemeDefinition(new Regex(@"^[\p{L}@_]+[\p{L}@_\d]*"), "Identifier"),
        new RegexLexemeDefinition(new Regex(@"^\b\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?m?"), "Number"),
        new RegexLexemeDefinition(new Regex(@"^[-+*/=]"), "Operator"),
        new RegexLexemeDefinition(new Regex(@"^[();]"), "Separator"),
        new RegexLexemeDefinition(new Regex(@"^\s*"), "Space", true),
    }.ToImmutableList();

    private static string[] _keywords =
    {
        "num",
        "string",
        "print",
    };

    public static Grammar Rules => new(new List<List<string>>()
    {
        new() { "Program", "StatementList" },
        new() { "StatementList", "StatementList", "Statement" },
        new() { "StatementList", "Statement" },
        new() { "Statement", "Declaration", ";" },
        new() { "Statement", "Assignment", ";" },
        new() { "Statement", "PrintStatement", ";" },
        new() { "Declaration", "type", "id" },
        new() { "Declaration", "type", "id", "=", "Expression" },
        new() { "Assignment", "id", "=", "Expression" },
        new() { "PrintStatement", "print", "(", "Expression", ")" },
        new() { "Expression", "Expression", "+", "Term" },
        new() { "Expression", "Expression", "-", "Term" },
        new() { "Expression", "Term" },
        new() { "Term", "Term", "*", "Exponent" },
        new() { "Term", "Term", "/", "Exponent" },
        new() { "Term", "Exponent" },
        new() { "Exponent", "Factor", "**", "Exponent" },
        new() { "Exponent", "Factor" },
        new() { "Factor", "(", "Expression", ")" },
        new() { "Factor", "number" },
        new() { "Factor", "id" },
        new() { "Factor", "Unary" },
        new() { "Unary", "-", "Factor" },
    });

    public static ImmutableList<Dictionary<string, int>> Actions => new List<Dictionary<string, int>>()
    {
        /*0*/  new() { { "type", 6 }, { "id", 7 }, { "print", 8 } },
        /*1*/  new() { { "type", 6 }, { "id", 7 }, { "print", 8 }, { "$", 0 } },
        /*2*/  new() { { "type", -2 }, { "id", -2 }, { "print", -2 }, { "$", -2 } },
        /*3*/  new() { { ";", 10 } },
        /*4*/  new() { { ";", 11 } },
        /*5*/  new() { { ";", 12 } },
        /*6*/  new() { { "id", 13 } },
        /*7*/  new() { { "=", 14 } },
        /*8*/  new() { { "(", 15 } },
        /*9*/  new() { { "type", -1 }, { "id", -1 }, { "print", -1 }, { "$", -1 } },
        /*10*/ new() { { "type", -3 }, { "id", -3 }, { "print", -3 }, { "$", -3 } },
        /*11*/ new() { { "type", -4 }, { "id", -4 }, { "print", -4 }, { "$", -4 } },
        /*12*/ new() { { "type", -5 }, { "id", -5 }, { "print", -5 }, { "$", -5 } },
        /*13*/ new() { { ";", -6 }, { "=", 16 } },
        /*14*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*15*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*16*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*17*/ new() { { ";", -8 }, { "+", 36 }, { "-", 37 } },
        /*18*/ new() { { ";", -12 }, { "+", -12 }, { "-", -12 }, { "*", 38 }, { "/", 39 } },
        /*19*/ new() { { ";", -15 }, { "+", -15 }, { "-", -15 }, { "*", -15 }, { "/", -15 } },
        /*20*/ new() { { ";", -17 }, { "+", -17 }, { "-", -17 }, { "*", -17 }, { "/", -17 }, { "**", 40 } },
        /*21*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*22*/ new() { { ";", -19 }, { "+", -19 }, { "-", -19 }, { "*", -19 }, { "/", -19 } },
        /*23*/ new() { { ";", -20 }, { "+", -20 }, { "-", -20 }, { "*", -20 }, { "/", -20 } },
        /*24*/ new() { { ";", -21 }, { "+", -21 }, { "-", -21 }, { "*", -21 }, { "/", -21 } },
        /*25*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*26*/ new() { { ")", 43 }, { "+", 44 }, { "-", 45 } },
        /*27*/ new() { { ")", -12 }, { "+", -12 }, { "-", -12 }, { "*", 46 }, { "/", 47 } },
        /*28*/ new() { { ")", -15 }, { "+", -15 }, { "-", -15 }, { "*", -15 }, { "/", -15 } },
        /*29*/ new() { { ")", -17 }, { "+", -17 }, { "-", -17 }, { "*", -17 }, { "/", -17 }, { "**", 48 } },
        /*30*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*31*/ new() { { ")", -19 }, { "+", -19 }, { "-", -19 }, { "*", -19 }, { "/", -19 }, { "**", -19 } },
        /*32*/ new() { { ")", -20 }, { "+", -20 }, { "-", -20 }, { "*", -20 }, { "/", -20 }, { "**", -20} },
        /*33*/ new() { { ")", -21 }, { "+", -21 }, { "-", -21 }, { "*", -21 }, { "/", -21 }, { "**", -21} },
        /*34*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*35*/ new() { { ";", -7 }, { "+", 36 }, { "-", 37 } },
        /*36*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*37*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*38*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*39*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*40*/ new() { { "id", 23 }, { "(", 21 }, { "-", 25 }, { "number", 22 } },
        /*41*/ new() { { ")", 56 }, { "+", 44 }, { "-", 45 } },
        /*42*/ new() { { ";", -22 }, { "+", -22 }, { "-", -22 }, { "*", -22 }, { "/", -22 }, { "**", -22} },
        /*43*/ new() { { ";", -9 } },
        /*44*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*45*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*46*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*47*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*48*/ new() { { "id", 32 }, { "(", 30 }, { "-", 34 }, { "number", 31 } },
        /*49*/ new() { { ")", 62 }, { "+", 44 }, { "-", 45 } },
        /*50*/ new() { { ")", -22 }, { "+", -22 }, { "-", -22 }, { "*", -22 }, { "/", -22 }, { "**", -22} },
        /*51*/ new() { { ";", -10 }, { "+", -10 }, { "-", -10 }, { "*", 38 }, { "/", 39 } },
        /*52*/ new() { { ";", -11 }, { "+", -11 }, { "-", -11 }, { "*", 38 }, { "/", 39 } },
        /*53*/ new() { { ";", -13 }, { "+", -13 }, { "-", -13 }, { "*", -13 }, { "/", -13 } },
        /*54*/ new() { { ";", -14 }, { "+", -14 }, { "-", -14 }, { "*", -14 }, { "/", -14 } },
        /*55*/ new() { { ";", -16 }, { "+", -16 }, { "-", -16 }, { "*", -16 }, { "/", -16 } },
        /*56*/ new() { { ";", -18 }, { "+", -18 }, { "-", -18 }, { "*", -18 }, { "/", -18 }, { "**", -18 } },
        /*57*/ new() { { ")", -10 }, { "+", -10 }, { "-", -10 }, { "*", 46 }, { "/", 47 } },
        /*58*/ new() { { ")", -11 }, { "+", -11 }, { "-", -11 }, { "*", 46 }, { "/", 47 } },
        /*59*/ new() { { ")", -13 }, { "+", -13 }, { "-", -13 }, { "*", -13 }, { "/", -13 } },
        /*60*/ new() { { ")", -14 }, { "+", -14 }, { "-", -14 }, { "*", -14 }, { "/", -14 } },
        /*61*/ new() { { ")", -16 }, { "+", -16 }, { "-", -16 }, { "*", -16 }, { "/", -16 } },
        /*62*/ new() { { ")", -18 }, { "+", -18 }, { "-", -18 }, { "*", -18 }, { "/", -18 }, { "**", -18 } },
    }.ToImmutableList();

    public static ImmutableList<Dictionary<string, int>> Goto => new List<Dictionary<string, int>>()
    {
        /*0*/  new() { { "StatementList", 1 }, { "Statement", 2 }, { "Declaration", 3 }, { "Assignment", 4 }, { "PrintStatement", 5 } },
        /*1*/  new() { { "Statement", 9 }, { "Declaration", 3 }, { "Assignment", 4 }, { "PrintStatement", 5 } },
        /*2*/  new(),
        /*3*/  new(),
        /*4*/  new(),
        /*5*/  new(),
        /*6*/  new(),
        /*7*/  new(),
        /*8*/  new(),
        /*9*/  new(),
        /*10*/ new(),
        /*11*/ new(),
        /*12*/ new(),
        /*13*/ new(),
        /*14*/ new() { { "Expression", 17 }, { "Term", 18 }, { "Exponent", 19 }, { "Factor", 20 }, { "Unary", 24 } },
        /*15*/ new() { { "Expression", 26 }, { "Term", 27 }, { "Exponent", 28 }, { "Factor", 29 }, { "Unary", 33 } },
        /*16*/ new() { { "Expression", 35 }, { "Term", 18 }, { "Exponent", 19 }, { "Factor", 20 }, { "Unary", 24 } },
        /*17*/ new(),
        /*18*/ new(),
        /*19*/ new(),
        /*20*/ new(),
        /*21*/ new() { { "Expression", 41 }, { "Term", 27 }, { "Exponent", 28 }, { "Factor", 29 }, { "Unary", 33 } },
        /*22*/ new(),
        /*23*/ new(),
        /*24*/ new(),
        /*25*/ new() { { "Factor", 42 }, { "Unary", 24 } },
        /*26*/ new(),
        /*27*/ new(),
        /*28*/ new(),
        /*29*/ new(),
        /*30*/ new() { { "Expression", 49 }, { "Term", 27 }, { "Exponent", 28 }, { "Factor", 29 }, { "Unary", 33 } },
        /*31*/ new(),
        /*32*/ new(),
        /*33*/ new(),
        /*34*/ new() { { "Factor", 50 }, { "Unary", 33 } },
        /*35*/ new(),
        /*36*/ new() { { "Term", 51 }, { "Exponent", 19 }, { "Factor", 20 }, { "Unary", 24 } },
        /*37*/ new() { { "Term", 52 }, { "Exponent", 19 }, { "Factor", 20 }, { "Unary", 24 } },
        /*38*/ new() { { "Exponent", 53 }, { "Factor", 20 }, { "Unary", 24 } },
        /*39*/ new() { { "Exponent", 54 }, { "Factor", 20 }, { "Unary", 24 } },
        /*40*/ new() { { "Exponent", 55 }, { "Factor", 20 }, { "Unary", 24 } },
        /*41*/ new(),
        /*42*/ new(),
        /*43*/ new(),
        /*44*/ new() { { "Term", 57 }, { "Exponent", 53 }, { "Factor", 29 }, { "Unary", 33 } },
        /*45*/ new() { { "Term", 58 }, { "Exponent", 53 }, { "Factor", 29 }, { "Unary", 33 } },
        /*46*/ new() { { "Exponent", 59 }, { "Factor", 29 }, { "Unary", 33 } },
        /*47*/ new() { { "Exponent", 60 }, { "Factor", 29 }, { "Unary", 33 } },
        /*48*/ new() { { "Exponent", 61 }, { "Factor", 29 }, { "Unary", 33 } },
    }.ToImmutableList();

    private static string GetKeywordPattern(string[] keywords) => $"^{string.Join("|", keywords)}";

}
